import {
  to = aws_s3_bucket.vectors
  id = "alex-vectors-448477198794"
}

import {
  to = aws_s3_bucket_versioning.vectors
  id = "alex-vectors-448477198794"
}

import {
  to = aws_s3_bucket_server_side_encryption_configuration.vectors
  id = "alex-vectors-448477198794"
}

import {
  to = aws_s3_bucket_public_access_block.vectors
  id = "alex-vectors-448477198794"
}

import {
  to = aws_iam_role.lambda_role
  id = "alex-ingest-lambda-role"
}

import {
  to = aws_iam_role_policy.lambda_policy
  id = "alex-ingest-lambda-role:alex-ingest-lambda-policy"
}

import {
  to = aws_lambda_function.ingest
  id = "alex-ingest"
}

import {
  to = aws_cloudwatch_log_group.lambda_logs
  id = "/aws/lambda/alex-ingest"
}

# API Gateway — REST API ID is generated by AWS, look it up with:
# aws apigateway get-rest-apis --query "items[?name=='alex-api'].id" --output text
# Then replace <REST_API_ID> below
import {
  to = aws_api_gateway_rest_api.api
  id = "<REST_API_ID>"
}

import {
  to = aws_api_gateway_resource.ingest
  id = "<REST_API_ID>/<RESOURCE_ID>"
}

import {
  to = aws_api_gateway_method.ingest_post
  id = "<REST_API_ID>/<RESOURCE_ID>/POST"
}

import {
  to = aws_api_gateway_integration.lambda
  id = "<REST_API_ID>/<RESOURCE_ID>/POST"
}

import {
  to = aws_lambda_permission.api_gateway
  id = "alex-ingest/AllowAPIGatewayInvoke"
}

import {
  to = aws_api_gateway_stage.api
  id = "<REST_API_ID>/prod"
}

import {
  to = aws_api_gateway_api_key.api_key
  id = "<API_KEY_ID>"
}

import {
  to = aws_api_gateway_usage_plan.plan
  id = "<USAGE_PLAN_ID>"
}

import {
  to = aws_api_gateway_usage_plan_key.plan_key
  id = "<USAGE_PLAN_ID>/<API_KEY_ID>"
}
